[build]
  base = "client/"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://ecommerce-platform-api.vercel.app/api"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_your_stripe_publishable_key_here"

[[redirects]]
  from = "/api/*"
  to = "https://ecommerce-platform-api.vercel.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "client/build"
